# Site settings
title: Sheffield GPU Hackathon 2019
email: rse@sheffield.ac.uk
url: http://gpuhack.shef.ac.uk
description: "Welcome to the website for Sheffield GPU Hackathon 2019 sponsored by NVIDIA."

# Color settings (hex-codes without the leading hash-tag)
color:
  primary-dark: '#000000'
  links: '#219ab3'

# Footer settings
footer: University of Sheffield

# Social networks usernames (many more available: google-plus, flickr, dribbble, pinterest, instagram, tumblr, linkedin, etc.)
#social:
#  - title: twitter
#    url: https://twitter.com/RSE_Sheffield

# Build settings
markdown: kramdown
permalink: pretty
