# Welcome to Jekyll!
#

# Site settings
title: Sheffield GPU Hackathon
description: 2020 July 27th - 31st, Halifax Hall
owner: Sheffield GPU Hackathon # or company name
first_published: 2019 # if migrating another site, the year of your first publish
email: p.richmond@sheffield.ac.uk
baseurl: "" # the subpath of your site, e.g. /blog
url: "https://gpuhack.shef.ac.uk" # the base hostname & protocol for your site
social:
  twitter: https://twitter.com/gpuhack
  github: https://github.com/GPUHackSheffield/GPUHackSheffield.github.io
  #linkedin-square: https://www.linkedin.com/company/9501702
  #facebook-official: https://facebook.com/<username>
  #google-plus-square: https://plus.google.com/u/0/+<username>
  email: mailto:gpuhack-organisers@sheffield.ac.uk
  #flickr:
  #instagram:
  #youtube-square:
  #spotify:
  #stack-overflow:
  #vimeo:
  #reddit:
  #stubleupon:
  #delicious:
  #pied-piper:
  #digg:
  #soundcloud:
  #deviantart:
  #angellist:
  #tumblr-square:
  #stackexchange:
  #weibo:
  #trello:
  #foursquare:
  #linux:
  #bitbucket-square:
  #vk:
  #slack:
  #vine:
  #weixin:
  #yelp:
  #skyatlas:
  #leanpub:
  #connectdevelop:
  #ils:
  #forumbee:
  #tripadvisor:
  #amazon:

# Build settings
markdown: kramdown
#sass:
#  style: compressed

collections:
  programmes:
    output: true
    permalink: /:collection/:path/
  landings:
    output: true
    permalink: /:collection/:path/
  committee:
    output: true
    permalink: /:collection/:path/        